[build]
  # Указываем команду для сборки проекта
  command = "npm run build"
  
  # Указываем папку для публикации (по умолчанию Vite использует dist/)
  publish = "dist"

[[redirects]]
  # Если у вас есть API или прокси, указываем редиректы
  from = "/api/*"
  to = "http://109.73.206.144:6969/:splat"
  status = 200
  force = true
